---
- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Reload SSHD service

- name: Ensure no empty password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
  notify: Reload SSHD service

- name: Turn on verbose logging
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#LogLevel'
    line: 'LogLevel VERBOSE'
  notify: Reload SSHD service

- name: Turn off X11Forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: 'X11Forwarding no'
  notify: Reload SSHD service
