version: '3'

services:
  static-server:
    build:
      context: .
    container_name: static-server
    ports:
      - "8022:22"
      - "8080:80"
    volumes:
      # - ./../static/images:/static/images
      - ./nginx/logs:/var/log/nginx
    tty: true
