---
- name: Ensure /static/images directory
  file:
    path: /static/images
    state: directory

- name: Copy static images to server
  copy:
    src: "{{ item }}"
    dest: /static/images/
  with_fileglob:
    - "{{ playbook_dir }}/../static/images/*"
  